language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install ./LumineerLabs/OMIR/
# command to run tests
script:
  - pytest ./LumineerLabs/OMIR/tests/